default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: notecase_development #CHANGE ME

test:
  <<: *default
  database: notecase_test #CHANGE ME

production:
  <<: *default
  database: notecase #CHANGE ME