default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: notecase_development 

test:
  <<: *default
  database: notecase_test 

production:
  <<: *default
  database: notecase_production