# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b558fb18cbab15cc6bb8cd0fc187b0ae18a958cd8fe064543389ea3eb0d6252381656a65b5404a52e671a68933bcd89f7a084be7fde596526cc14e752c5ee8ce

test:
  secret_key_base: 5754ff6602b9bfc90089b8fa8a1bf9d0ccecf3bc22c01ca820710c48162bdf7fa40760ca5584abfb91fc4a3bed8b00bb2dd67222f5893705ba2a83d43a52b3e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
